version: '3.4' # specify docker-compose version

networks:
  backend:

# Define the services/containers to be run
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - backend

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    networks:
      - backend

  minio:
    image: minio/minio:RELEASE.2022-05-19T18-20-59Z
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        echo "Starting minio"
        minio server /data --console-address ":9001"
        echo "Minio started"
    networks:
      - backend
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
